#!/usr/bin/env bash
# Usage: adv list <state>
#
# Summary: List your instances
#
# Help:
#   See a list of your instances and data about their state and
#   how to connect with them. Shows active instances by default if
#   no state is passed in. Permitted states are: active*, inactive*, initialized, provisioning,
#   running, pending_expiration, failed, and expired.
#
#   * These are meta-states encompassing a subset of the remaining options
#   * active = initialized, provisioning, running, pending_expiration
#   * inactive = failed, expired
#
#   adv list
#   adv ls
#   adv ls running
#   adv ls expired
#

set -e

unset -f _run
_run(){
  load_functions authentication instances/listing

  check_authenticated

  if [[ $adv_authenticated == true ]]
  then
    local default_state=('active')
    local state=${1:-$default_state}
    list_instances $state
  else
    login
    rerun
  fi
}

source "$_ADV_ROOT/libexec/functions/common.bash"
cache_run $0 $@
prepare_arguments $original_args
_run ${script_args[@]}
