#!/usr/bin/env bash
# Usage: adv try [<service1> <service2> ...]
#
# Summary: Try out Adventure by provisioning a Redis instance
#
# Help:
#   Try out Adventure by provisioning some standalone instances. When called
#   with no arguments, it defaults to Redis.
#
#   adv try
#   adv try <service>
#   adv try <service1> <service2> ...
#

set -e

unset -f _run
_run(){
  load_functions authentication provisioning

  check_authenticated

  if [[ $adv_authenticated == true ]]
  then
    local default_services=('redis')
    local services=${@:-$default_services}
    provision_services $services
  else
    login
    rerun
  fi
}

source "$_ADV_ROOT/libexec/functions/common.bash"
cache_run $0 $@
prepare_arguments $original_args
_run ${script_args[@]}
