#!/usr/bin/env bash
# Usage: adv login
# Summary: Login or register an Adventure account
# Help:
#   adv login

set -e
echo "
Follow the instructions below to potentially create
and login to your Adventure account
"

read -p 'Email: ' email
read -s -p 'Password: ' password
