#!/usr/bin/env bash
# Usage: adv provision <env-name>
# Summary: Provision resources based on $PWD
# Help:
# This (recursively) scans the current working directory
#   and provisions the necessary resources.
#
# An optional environment name can be provided for grouping.
#
#   adv provision
#   adv provision <env-name>

set -e

files=('Gemfile' 'Gemfile.lock' 'package.json')
services=('redis' 'mongo' 'couch' 'postgres' 'mysql')

for file in "${files[@]}"
do
  path="./$file"
  if [ -e $path ]
  then
    $_ADV_ROOT/bin/adv scanfile $path
  fi
done
